// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: tag/v1/service_internal.proto

package tag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagIDTreeizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to From:
	//
	//	*GetTagIDTreeizeRequest_TagId
	//	*GetTagIDTreeizeRequest_TypeId
	From isGetTagIDTreeizeRequest_From `protobuf_oneof:"from"`
}

func (x *GetTagIDTreeizeRequest) Reset() {
	*x = GetTagIDTreeizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagIDTreeizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagIDTreeizeRequest) ProtoMessage() {}

func (x *GetTagIDTreeizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagIDTreeizeRequest.ProtoReflect.Descriptor instead.
func (*GetTagIDTreeizeRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{0}
}

func (m *GetTagIDTreeizeRequest) GetFrom() isGetTagIDTreeizeRequest_From {
	if m != nil {
		return m.From
	}
	return nil
}

func (x *GetTagIDTreeizeRequest) GetTagId() uint64 {
	if x, ok := x.GetFrom().(*GetTagIDTreeizeRequest_TagId); ok {
		return x.TagId
	}
	return 0
}

func (x *GetTagIDTreeizeRequest) GetTypeId() uint64 {
	if x, ok := x.GetFrom().(*GetTagIDTreeizeRequest_TypeId); ok {
		return x.TypeId
	}
	return 0
}

type isGetTagIDTreeizeRequest_From interface {
	isGetTagIDTreeizeRequest_From()
}

type GetTagIDTreeizeRequest_TagId struct {
	TagId uint64 `protobuf:"fixed64,1,opt,name=tag_id,json=tagId,proto3,oneof"`
}

type GetTagIDTreeizeRequest_TypeId struct {
	TypeId uint64 `protobuf:"fixed64,2,opt,name=type_id,json=typeId,proto3,oneof"`
}

func (*GetTagIDTreeizeRequest_TagId) isGetTagIDTreeizeRequest_From() {}

func (*GetTagIDTreeizeRequest_TypeId) isGetTagIDTreeizeRequest_From() {}

type GetTagIDTreeizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TagIDTreeize `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type *Type         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetTagIDTreeizeResponse) Reset() {
	*x = GetTagIDTreeizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagIDTreeizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagIDTreeizeResponse) ProtoMessage() {}

func (x *GetTagIDTreeizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagIDTreeizeResponse.ProtoReflect.Descriptor instead.
func (*GetTagIDTreeizeResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagIDTreeizeResponse) GetData() *TagIDTreeize {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTagIDTreeizeResponse) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type TagIDTreeize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64          `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Child []*TagIDTreeize `protobuf:"bytes,2,rep,name=child,proto3" json:"child,omitempty"`
}

func (x *TagIDTreeize) Reset() {
	*x = TagIDTreeize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagIDTreeize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagIDTreeize) ProtoMessage() {}

func (x *TagIDTreeize) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagIDTreeize.ProtoReflect.Descriptor instead.
func (*TagIDTreeize) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{2}
}

func (x *TagIDTreeize) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagIDTreeize) GetChild() []*TagIDTreeize {
	if x != nil {
		return x.Child
	}
	return nil
}

type BindRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId   uint64           `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId uint64           `protobuf:"fixed64,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	TagId      uint64           `protobuf:"fixed64,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Data       *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BindRelationRequest) Reset() {
	*x = BindRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRelationRequest) ProtoMessage() {}

func (x *BindRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRelationRequest.ProtoReflect.Descriptor instead.
func (*BindRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{3}
}

func (x *BindRelationRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *BindRelationRequest) GetExternalId() uint64 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *BindRelationRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *BindRelationRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CleanTagId   []uint64 `protobuf:"fixed64,1,rep,packed,name=clean_tag_id,json=cleanTagId,proto3" json:"clean_tag_id,omitempty"`
	InheritTagId []uint64 `protobuf:"fixed64,2,rep,packed,name=inherit_tag_id,json=inheritTagId,proto3" json:"inherit_tag_id,omitempty"`
}

func (x *BindRelationResponse) Reset() {
	*x = BindRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRelationResponse) ProtoMessage() {}

func (x *BindRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRelationResponse.ProtoReflect.Descriptor instead.
func (*BindRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{4}
}

func (x *BindRelationResponse) GetCleanTagId() []uint64 {
	if x != nil {
		return x.CleanTagId
	}
	return nil
}

func (x *BindRelationResponse) GetInheritTagId() []uint64 {
	if x != nil {
		return x.InheritTagId
	}
	return nil
}

type BindTagToExternalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId   uint64   `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId uint64   `protobuf:"fixed64,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	TagId      []uint64 `protobuf:"fixed64,3,rep,packed,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *BindTagToExternalRequest) Reset() {
	*x = BindTagToExternalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindTagToExternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTagToExternalRequest) ProtoMessage() {}

func (x *BindTagToExternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTagToExternalRequest.ProtoReflect.Descriptor instead.
func (*BindTagToExternalRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{5}
}

func (x *BindTagToExternalRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *BindTagToExternalRequest) GetExternalId() uint64 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *BindTagToExternalRequest) GetTagId() []uint64 {
	if x != nil {
		return x.TagId
	}
	return nil
}

type BindTagToExternalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CleanTagId   []uint64 `protobuf:"fixed64,1,rep,packed,name=clean_tag_id,json=cleanTagId,proto3" json:"clean_tag_id,omitempty"`
	InheritTagId []uint64 `protobuf:"fixed64,2,rep,packed,name=inherit_tag_id,json=inheritTagId,proto3" json:"inherit_tag_id,omitempty"`
}

func (x *BindTagToExternalResponse) Reset() {
	*x = BindTagToExternalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindTagToExternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTagToExternalResponse) ProtoMessage() {}

func (x *BindTagToExternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTagToExternalResponse.ProtoReflect.Descriptor instead.
func (*BindTagToExternalResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{6}
}

func (x *BindTagToExternalResponse) GetCleanTagId() []uint64 {
	if x != nil {
		return x.CleanTagId
	}
	return nil
}

func (x *BindTagToExternalResponse) GetInheritTagId() []uint64 {
	if x != nil {
		return x.InheritTagId
	}
	return nil
}

type UnbindRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId   uint64 `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId uint64 `protobuf:"fixed64,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	TagId      uint64 `protobuf:"fixed64,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *UnbindRelationRequest) Reset() {
	*x = UnbindRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbindRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRelationRequest) ProtoMessage() {}

func (x *UnbindRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRelationRequest.ProtoReflect.Descriptor instead.
func (*UnbindRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{7}
}

func (x *UnbindRelationRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *UnbindRelationRequest) GetExternalId() uint64 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *UnbindRelationRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type UnbindRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CleanTagId []uint64 `protobuf:"fixed64,1,rep,packed,name=clean_tag_id,json=cleanTagId,proto3" json:"clean_tag_id,omitempty"`
}

func (x *UnbindRelationResponse) Reset() {
	*x = UnbindRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbindRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRelationResponse) ProtoMessage() {}

func (x *UnbindRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRelationResponse.ProtoReflect.Descriptor instead.
func (*UnbindRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{8}
}

func (x *UnbindRelationResponse) GetCleanTagId() []uint64 {
	if x != nil {
		return x.CleanTagId
	}
	return nil
}

type GetAllByModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId uint64 `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
}

func (x *GetAllByModuleRequest) Reset() {
	*x = GetAllByModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllByModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByModuleRequest) ProtoMessage() {}

func (x *GetAllByModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByModuleRequest.ProtoReflect.Descriptor instead.
func (*GetAllByModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllByModuleRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

type GetAllByModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type []*Type `protobuf:"bytes,1,rep,name=type,proto3" json:"type,omitempty"`
	Tag  []*Tag  `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetAllByModuleResponse) Reset() {
	*x = GetAllByModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllByModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByModuleResponse) ProtoMessage() {}

func (x *GetAllByModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByModuleResponse.ProtoReflect.Descriptor instead.
func (*GetAllByModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllByModuleResponse) GetType() []*Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GetAllByModuleResponse) GetTag() []*Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type RegisterModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RegisterModuleRequest) Reset() {
	*x = RegisterModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleRequest) ProtoMessage() {}

func (x *RegisterModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleRequest.ProtoReflect.Descriptor instead.
func (*RegisterModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterModuleRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RegisterModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Module `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RegisterModuleResponse) Reset() {
	*x = RegisterModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleResponse) ProtoMessage() {}

func (x *RegisterModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleResponse.ProtoReflect.Descriptor instead.
func (*RegisterModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterModuleResponse) GetData() *Module {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Tag `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // only allow write key/data, key: {module-key}:{type-key}:{tag-key}
}

func (x *RegisterTagRequest) Reset() {
	*x = RegisterTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTagRequest) ProtoMessage() {}

func (x *RegisterTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTagRequest.ProtoReflect.Descriptor instead.
func (*RegisterTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterTagRequest) GetData() []*Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Tag `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *RegisterTagResponse) Reset() {
	*x = RegisterTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTagResponse) ProtoMessage() {}

func (x *RegisterTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTagResponse.ProtoReflect.Descriptor instead.
func (*RegisterTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterTagResponse) GetData() []*Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetTypeWithModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId  uint64           `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	TypeId    *uint64          `protobuf:"fixed64,2,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id,omitempty"` // is empty, will be add
	Key       *string          `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`                       // is empty, will be automatically generated
	Info      *structpb.Struct `protobuf:"bytes,4,opt,name=info,proto3,oneof" json:"info,omitempty"`
	Inherit   *bool            `protobuf:"varint,5,opt,name=inherit,proto3,oneof" json:"inherit,omitempty"`
	Exclusive *bool            `protobuf:"varint,6,opt,name=exclusive,proto3,oneof" json:"exclusive,omitempty"`
}

func (x *SetTypeWithModuleRequest) Reset() {
	*x = SetTypeWithModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypeWithModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypeWithModuleRequest) ProtoMessage() {}

func (x *SetTypeWithModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypeWithModuleRequest.ProtoReflect.Descriptor instead.
func (*SetTypeWithModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{15}
}

func (x *SetTypeWithModuleRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *SetTypeWithModuleRequest) GetTypeId() uint64 {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return 0
}

func (x *SetTypeWithModuleRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *SetTypeWithModuleRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SetTypeWithModuleRequest) GetInherit() bool {
	if x != nil && x.Inherit != nil {
		return *x.Inherit
	}
	return false
}

func (x *SetTypeWithModuleRequest) GetExclusive() bool {
	if x != nil && x.Exclusive != nil {
		return *x.Exclusive
	}
	return false
}

type SetTypeWithModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Type `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetTypeWithModuleResponse) Reset() {
	*x = SetTypeWithModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypeWithModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypeWithModuleResponse) ProtoMessage() {}

func (x *SetTypeWithModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypeWithModuleResponse.ProtoReflect.Descriptor instead.
func (*SetTypeWithModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{16}
}

func (x *SetTypeWithModuleResponse) GetData() *Type {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteTypeWithModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId uint64   `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	TypeId   []uint64 `protobuf:"fixed64,2,rep,packed,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
}

func (x *DeleteTypeWithModuleRequest) Reset() {
	*x = DeleteTypeWithModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTypeWithModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTypeWithModuleRequest) ProtoMessage() {}

func (x *DeleteTypeWithModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTypeWithModuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteTypeWithModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteTypeWithModuleRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *DeleteTypeWithModuleRequest) GetTypeId() []uint64 {
	if x != nil {
		return x.TypeId
	}
	return nil
}

type DeleteTypeWithModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTypeWithModuleResponse) Reset() {
	*x = DeleteTypeWithModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTypeWithModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTypeWithModuleResponse) ProtoMessage() {}

func (x *DeleteTypeWithModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTypeWithModuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteTypeWithModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{18}
}

type SetTagWithModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId uint64           `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	TagId    *uint64          `protobuf:"fixed64,2,opt,name=tag_id,json=tagId,proto3,oneof" json:"tag_id,omitempty"`
	Key      *string          `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	TypeId   *uint64          `protobuf:"fixed64,4,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id,omitempty"`
	ParentId *uint64          `protobuf:"fixed64,5,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Data     *structpb.Struct `protobuf:"bytes,6,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Info     *structpb.Struct `protobuf:"bytes,7,opt,name=info,proto3,oneof" json:"info,omitempty"`
}

func (x *SetTagWithModuleRequest) Reset() {
	*x = SetTagWithModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagWithModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagWithModuleRequest) ProtoMessage() {}

func (x *SetTagWithModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagWithModuleRequest.ProtoReflect.Descriptor instead.
func (*SetTagWithModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{19}
}

func (x *SetTagWithModuleRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *SetTagWithModuleRequest) GetTagId() uint64 {
	if x != nil && x.TagId != nil {
		return *x.TagId
	}
	return 0
}

func (x *SetTagWithModuleRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *SetTagWithModuleRequest) GetTypeId() uint64 {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return 0
}

func (x *SetTagWithModuleRequest) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *SetTagWithModuleRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SetTagWithModuleRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetTagWithModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTagWithModuleResponse) Reset() {
	*x = SetTagWithModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagWithModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagWithModuleResponse) ProtoMessage() {}

func (x *SetTagWithModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagWithModuleResponse.ProtoReflect.Descriptor instead.
func (*SetTagWithModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{20}
}

type DeleteTagWithModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId uint64   `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	TagId    []uint64 `protobuf:"fixed64,2,rep,packed,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DeleteTagWithModuleRequest) Reset() {
	*x = DeleteTagWithModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagWithModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagWithModuleRequest) ProtoMessage() {}

func (x *DeleteTagWithModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagWithModuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagWithModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteTagWithModuleRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *DeleteTagWithModuleRequest) GetTagId() []uint64 {
	if x != nil {
		return x.TagId
	}
	return nil
}

type DeleteTagWithModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTagWithModuleResponse) Reset() {
	*x = DeleteTagWithModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_internal_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagWithModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagWithModuleResponse) ProtoMessage() {}

func (x *DeleteTagWithModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_internal_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagWithModuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagWithModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_internal_proto_rawDescGZIP(), []int{22}
}

var File_tag_v1_service_internal_proto protoreflect.FileDescriptor

var file_tag_v1_service_internal_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x74, 0x61, 0x67, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x54, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72, 0x65, 0x65, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x06, 0x74, 0x61, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x05, 0x74, 0x61, 0x67,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x42, 0x06, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x65, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49,
	0x44, 0x54, 0x72, 0x65, 0x65, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72, 0x65,
	0x65, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4a, 0x0a, 0x0c,
	0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72, 0x65, 0x65, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x05,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72, 0x65, 0x65, 0x69, 0x7a,
	0x65, 0x52, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x13, 0x42, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05,
	0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x5e, 0x0a, 0x14, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x63, 0x6c,
	0x65, 0x61, 0x6e, 0x5f, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06,
	0x52, 0x0a, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x61, 0x67, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e,
	0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x06, 0x52, 0x0c, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x54, 0x61, 0x67,
	0x49, 0x64, 0x22, 0x6f, 0x0a, 0x18, 0x42, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x54, 0x6f, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x06, 0x52, 0x05, 0x74, 0x61,
	0x67, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x19, 0x42, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x54, 0x6f,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0c, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0a, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x61, 0x67,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x5f, 0x74, 0x61,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0c, 0x69, 0x6e, 0x68, 0x65,
	0x72, 0x69, 0x74, 0x54, 0x61, 0x67, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x15, 0x55, 0x6e, 0x62, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x16, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0c, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0a, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x61, 0x67,
	0x49, 0x64, 0x22, 0x34, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x42, 0x79, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x22, 0x29, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3c,
	0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x12,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x97, 0x02, 0x0a, 0x18,
	0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x48, 0x02, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07,
	0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52,
	0x07, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x04,
	0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b,
	0x65, 0x79, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x78, 0x63, 0x6c,
	0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0x3d, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x06, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xcc, 0x02, 0x0a, 0x17, 0x53, 0x65,
	0x74, 0x54, 0x61, 0x67, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x06, 0x48, 0x00, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x15,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x48, 0x02, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x06, 0x48, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x04, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x05,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61,
	0x67, 0x5f, 0x69, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x54,
	0x61, 0x67, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x50, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61,
	0x67, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x06, 0x52,
	0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x61, 0x67, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xec, 0x06, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72,
	0x65, 0x65, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72, 0x65, 0x65, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x44, 0x54, 0x72, 0x65, 0x65, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x42, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x42, 0x79, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48,
	0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x1a, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x20, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x23, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x53, 0x65, 0x74,
	0x54, 0x61, 0x67, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1f, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x57, 0x69, 0x74,
	0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x60, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x57,
	0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x22, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x57, 0x69, 0x74, 0x68,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67,
	0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x74,
	0x61, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tag_v1_service_internal_proto_rawDescOnce sync.Once
	file_tag_v1_service_internal_proto_rawDescData = file_tag_v1_service_internal_proto_rawDesc
)

func file_tag_v1_service_internal_proto_rawDescGZIP() []byte {
	file_tag_v1_service_internal_proto_rawDescOnce.Do(func() {
		file_tag_v1_service_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_tag_v1_service_internal_proto_rawDescData)
	})
	return file_tag_v1_service_internal_proto_rawDescData
}

var file_tag_v1_service_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_tag_v1_service_internal_proto_goTypes = []any{
	(*GetTagIDTreeizeRequest)(nil),       // 0: tag.v1.GetTagIDTreeizeRequest
	(*GetTagIDTreeizeResponse)(nil),      // 1: tag.v1.GetTagIDTreeizeResponse
	(*TagIDTreeize)(nil),                 // 2: tag.v1.TagIDTreeize
	(*BindRelationRequest)(nil),          // 3: tag.v1.BindRelationRequest
	(*BindRelationResponse)(nil),         // 4: tag.v1.BindRelationResponse
	(*BindTagToExternalRequest)(nil),     // 5: tag.v1.BindTagToExternalRequest
	(*BindTagToExternalResponse)(nil),    // 6: tag.v1.BindTagToExternalResponse
	(*UnbindRelationRequest)(nil),        // 7: tag.v1.UnbindRelationRequest
	(*UnbindRelationResponse)(nil),       // 8: tag.v1.UnbindRelationResponse
	(*GetAllByModuleRequest)(nil),        // 9: tag.v1.GetAllByModuleRequest
	(*GetAllByModuleResponse)(nil),       // 10: tag.v1.GetAllByModuleResponse
	(*RegisterModuleRequest)(nil),        // 11: tag.v1.RegisterModuleRequest
	(*RegisterModuleResponse)(nil),       // 12: tag.v1.RegisterModuleResponse
	(*RegisterTagRequest)(nil),           // 13: tag.v1.RegisterTagRequest
	(*RegisterTagResponse)(nil),          // 14: tag.v1.RegisterTagResponse
	(*SetTypeWithModuleRequest)(nil),     // 15: tag.v1.SetTypeWithModuleRequest
	(*SetTypeWithModuleResponse)(nil),    // 16: tag.v1.SetTypeWithModuleResponse
	(*DeleteTypeWithModuleRequest)(nil),  // 17: tag.v1.DeleteTypeWithModuleRequest
	(*DeleteTypeWithModuleResponse)(nil), // 18: tag.v1.DeleteTypeWithModuleResponse
	(*SetTagWithModuleRequest)(nil),      // 19: tag.v1.SetTagWithModuleRequest
	(*SetTagWithModuleResponse)(nil),     // 20: tag.v1.SetTagWithModuleResponse
	(*DeleteTagWithModuleRequest)(nil),   // 21: tag.v1.DeleteTagWithModuleRequest
	(*DeleteTagWithModuleResponse)(nil),  // 22: tag.v1.DeleteTagWithModuleResponse
	(*Type)(nil),                         // 23: tag.v1.Type
	(*structpb.Struct)(nil),              // 24: google.protobuf.Struct
	(*Tag)(nil),                          // 25: tag.v1.Tag
	(*Module)(nil),                       // 26: tag.v1.Module
}
var file_tag_v1_service_internal_proto_depIdxs = []int32{
	2,  // 0: tag.v1.GetTagIDTreeizeResponse.data:type_name -> tag.v1.TagIDTreeize
	23, // 1: tag.v1.GetTagIDTreeizeResponse.type:type_name -> tag.v1.Type
	2,  // 2: tag.v1.TagIDTreeize.child:type_name -> tag.v1.TagIDTreeize
	24, // 3: tag.v1.BindRelationRequest.data:type_name -> google.protobuf.Struct
	23, // 4: tag.v1.GetAllByModuleResponse.type:type_name -> tag.v1.Type
	25, // 5: tag.v1.GetAllByModuleResponse.tag:type_name -> tag.v1.Tag
	26, // 6: tag.v1.RegisterModuleResponse.data:type_name -> tag.v1.Module
	25, // 7: tag.v1.RegisterTagRequest.data:type_name -> tag.v1.Tag
	25, // 8: tag.v1.RegisterTagResponse.data:type_name -> tag.v1.Tag
	24, // 9: tag.v1.SetTypeWithModuleRequest.info:type_name -> google.protobuf.Struct
	23, // 10: tag.v1.SetTypeWithModuleResponse.data:type_name -> tag.v1.Type
	24, // 11: tag.v1.SetTagWithModuleRequest.data:type_name -> google.protobuf.Struct
	24, // 12: tag.v1.SetTagWithModuleRequest.info:type_name -> google.protobuf.Struct
	0,  // 13: tag.v1.Internal.GetTagIDTreeize:input_type -> tag.v1.GetTagIDTreeizeRequest
	3,  // 14: tag.v1.Internal.BindRelation:input_type -> tag.v1.BindRelationRequest
	7,  // 15: tag.v1.Internal.UnbindRelation:input_type -> tag.v1.UnbindRelationRequest
	9,  // 16: tag.v1.Internal.GetAllByModule:input_type -> tag.v1.GetAllByModuleRequest
	11, // 17: tag.v1.Internal.RegisterModule:input_type -> tag.v1.RegisterModuleRequest
	13, // 18: tag.v1.Internal.RegisterTag:input_type -> tag.v1.RegisterTagRequest
	15, // 19: tag.v1.Internal.SetTypeWithModule:input_type -> tag.v1.SetTypeWithModuleRequest
	17, // 20: tag.v1.Internal.DeleteTypeWithModule:input_type -> tag.v1.DeleteTypeWithModuleRequest
	19, // 21: tag.v1.Internal.SetTagWithModule:input_type -> tag.v1.SetTagWithModuleRequest
	21, // 22: tag.v1.Internal.DeleteTagWithModule:input_type -> tag.v1.DeleteTagWithModuleRequest
	1,  // 23: tag.v1.Internal.GetTagIDTreeize:output_type -> tag.v1.GetTagIDTreeizeResponse
	4,  // 24: tag.v1.Internal.BindRelation:output_type -> tag.v1.BindRelationResponse
	8,  // 25: tag.v1.Internal.UnbindRelation:output_type -> tag.v1.UnbindRelationResponse
	10, // 26: tag.v1.Internal.GetAllByModule:output_type -> tag.v1.GetAllByModuleResponse
	12, // 27: tag.v1.Internal.RegisterModule:output_type -> tag.v1.RegisterModuleResponse
	14, // 28: tag.v1.Internal.RegisterTag:output_type -> tag.v1.RegisterTagResponse
	16, // 29: tag.v1.Internal.SetTypeWithModule:output_type -> tag.v1.SetTypeWithModuleResponse
	18, // 30: tag.v1.Internal.DeleteTypeWithModule:output_type -> tag.v1.DeleteTypeWithModuleResponse
	20, // 31: tag.v1.Internal.SetTagWithModule:output_type -> tag.v1.SetTagWithModuleResponse
	22, // 32: tag.v1.Internal.DeleteTagWithModule:output_type -> tag.v1.DeleteTagWithModuleResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tag_v1_service_internal_proto_init() }
func file_tag_v1_service_internal_proto_init() {
	if File_tag_v1_service_internal_proto != nil {
		return
	}
	file_tag_v1_tag_proto_init()
	file_tag_v1_type_proto_init()
	file_tag_v1_module_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tag_v1_service_internal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTagIDTreeizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTagIDTreeizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TagIDTreeize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BindRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BindRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BindTagToExternalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*BindTagToExternalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UnbindRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UnbindRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllByModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllByModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SetTypeWithModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*SetTypeWithModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTypeWithModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTypeWithModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagWithModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagWithModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagWithModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_internal_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagWithModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tag_v1_service_internal_proto_msgTypes[0].OneofWrappers = []any{
		(*GetTagIDTreeizeRequest_TagId)(nil),
		(*GetTagIDTreeizeRequest_TypeId)(nil),
	}
	file_tag_v1_service_internal_proto_msgTypes[15].OneofWrappers = []any{}
	file_tag_v1_service_internal_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tag_v1_service_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_v1_service_internal_proto_goTypes,
		DependencyIndexes: file_tag_v1_service_internal_proto_depIdxs,
		MessageInfos:      file_tag_v1_service_internal_proto_msgTypes,
	}.Build()
	File_tag_v1_service_internal_proto = out.File
	file_tag_v1_service_internal_proto_rawDesc = nil
	file_tag_v1_service_internal_proto_goTypes = nil
	file_tag_v1_service_internal_proto_depIdxs = nil
}
