// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: tag/v1/service_relation.proto

package tag

import (
	v1 "github.com/core-pb/dt/query/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *v1.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort       []*v1.Sort       `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty"`
	ModuleId   []uint64         `protobuf:"fixed64,3,rep,packed,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId []uint64         `protobuf:"fixed64,4,rep,packed,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	TagId      []uint64         `protobuf:"fixed64,5,rep,packed,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	SourceId   []uint64         `protobuf:"fixed64,6,rep,packed,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Data       *structpb.Struct `protobuf:"bytes,7,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *ListRelationRequest) Reset() {
	*x = ListRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationRequest) ProtoMessage() {}

func (x *ListRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationRequest.ProtoReflect.Descriptor instead.
func (*ListRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{0}
}

func (x *ListRelationRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRelationRequest) GetSort() []*v1.Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListRelationRequest) GetModuleId() []uint64 {
	if x != nil {
		return x.ModuleId
	}
	return nil
}

func (x *ListRelationRequest) GetExternalId() []uint64 {
	if x != nil {
		return x.ExternalId
	}
	return nil
}

func (x *ListRelationRequest) GetTagId() []uint64 {
	if x != nil {
		return x.TagId
	}
	return nil
}

func (x *ListRelationRequest) GetSourceId() []uint64 {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *ListRelationRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*Relation `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count int64       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListRelationResponse) Reset() {
	*x = ListRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationResponse) ProtoMessage() {}

func (x *ListRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationResponse.ProtoReflect.Descriptor instead.
func (*ListRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{1}
}

func (x *ListRelationResponse) GetData() []*Relation {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListRelationResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId   uint64           `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId uint64           `protobuf:"fixed64,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	TagId      uint64           `protobuf:"fixed64,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Data       *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetRelationRequest) Reset() {
	*x = SetRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelationRequest) ProtoMessage() {}

func (x *SetRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelationRequest.ProtoReflect.Descriptor instead.
func (*SetRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{2}
}

func (x *SetRelationRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *SetRelationRequest) GetExternalId() uint64 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *SetRelationRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *SetRelationRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRelationResponse) Reset() {
	*x = SetRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelationResponse) ProtoMessage() {}

func (x *SetRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelationResponse.ProtoReflect.Descriptor instead.
func (*SetRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{3}
}

type DeleteRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId   uint64 `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId uint64 `protobuf:"fixed64,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	TagId      uint64 `protobuf:"fixed64,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DeleteRelationRequest) Reset() {
	*x = DeleteRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationRequest) ProtoMessage() {}

func (x *DeleteRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRelationRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *DeleteRelationRequest) GetExternalId() uint64 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *DeleteRelationRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRelationResponse) Reset() {
	*x = DeleteRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationResponse) ProtoMessage() {}

func (x *DeleteRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{5}
}

type DestroyExternalRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId   uint64   `protobuf:"fixed64,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ExternalId []uint64 `protobuf:"fixed64,2,rep,packed,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
}

func (x *DestroyExternalRelationRequest) Reset() {
	*x = DestroyExternalRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyExternalRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyExternalRelationRequest) ProtoMessage() {}

func (x *DestroyExternalRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyExternalRelationRequest.ProtoReflect.Descriptor instead.
func (*DestroyExternalRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyExternalRelationRequest) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *DestroyExternalRelationRequest) GetExternalId() []uint64 {
	if x != nil {
		return x.ExternalId
	}
	return nil
}

type DestroyExternalRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyExternalRelationResponse) Reset() {
	*x = DestroyExternalRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyExternalRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyExternalRelationResponse) ProtoMessage() {}

func (x *DestroyExternalRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyExternalRelationResponse.ProtoReflect.Descriptor instead.
func (*DestroyExternalRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{7}
}

type DestroyTagRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId    uint64   `protobuf:"fixed64,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ModuleId []uint64 `protobuf:"fixed64,2,rep,packed,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
}

func (x *DestroyTagRelationRequest) Reset() {
	*x = DestroyTagRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyTagRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyTagRelationRequest) ProtoMessage() {}

func (x *DestroyTagRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyTagRelationRequest.ProtoReflect.Descriptor instead.
func (*DestroyTagRelationRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyTagRelationRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *DestroyTagRelationRequest) GetModuleId() []uint64 {
	if x != nil {
		return x.ModuleId
	}
	return nil
}

type DestroyTagRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyTagRelationResponse) Reset() {
	*x = DestroyTagRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_relation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyTagRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyTagRelationResponse) ProtoMessage() {}

func (x *DestroyTagRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_relation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyTagRelationResponse.ProtoReflect.Descriptor instead.
func (*DestroyTagRelationResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_relation_proto_rawDescGZIP(), []int{9}
}

var File_tag_v1_service_relation_proto protoreflect.FileDescriptor

var file_tag_v1_service_relation_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x72,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x02, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x06,
	0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x06, 0x52, 0x05, 0x74, 0x61,
	0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x06, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88,
	0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x96, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x6c, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x18, 0x0a,
	0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x1e, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0a, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x1f, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x19, 0x44, 0x65,
	0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc5, 0x03, 0x0a, 0x0c, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x12, 0x4b, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x51, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x26, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5d, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2d, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x74, 0x61, 0x67, 0x2f,
	0x76, 0x31, 0x3b, 0x74, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tag_v1_service_relation_proto_rawDescOnce sync.Once
	file_tag_v1_service_relation_proto_rawDescData = file_tag_v1_service_relation_proto_rawDesc
)

func file_tag_v1_service_relation_proto_rawDescGZIP() []byte {
	file_tag_v1_service_relation_proto_rawDescOnce.Do(func() {
		file_tag_v1_service_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_tag_v1_service_relation_proto_rawDescData)
	})
	return file_tag_v1_service_relation_proto_rawDescData
}

var file_tag_v1_service_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tag_v1_service_relation_proto_goTypes = []any{
	(*ListRelationRequest)(nil),             // 0: tag.v1.ListRelationRequest
	(*ListRelationResponse)(nil),            // 1: tag.v1.ListRelationResponse
	(*SetRelationRequest)(nil),              // 2: tag.v1.SetRelationRequest
	(*SetRelationResponse)(nil),             // 3: tag.v1.SetRelationResponse
	(*DeleteRelationRequest)(nil),           // 4: tag.v1.DeleteRelationRequest
	(*DeleteRelationResponse)(nil),          // 5: tag.v1.DeleteRelationResponse
	(*DestroyExternalRelationRequest)(nil),  // 6: tag.v1.DestroyExternalRelationRequest
	(*DestroyExternalRelationResponse)(nil), // 7: tag.v1.DestroyExternalRelationResponse
	(*DestroyTagRelationRequest)(nil),       // 8: tag.v1.DestroyTagRelationRequest
	(*DestroyTagRelationResponse)(nil),      // 9: tag.v1.DestroyTagRelationResponse
	(*v1.Pagination)(nil),                   // 10: query.v1.Pagination
	(*v1.Sort)(nil),                         // 11: query.v1.Sort
	(*structpb.Struct)(nil),                 // 12: google.protobuf.Struct
	(*Relation)(nil),                        // 13: tag.v1.Relation
}
var file_tag_v1_service_relation_proto_depIdxs = []int32{
	10, // 0: tag.v1.ListRelationRequest.pagination:type_name -> query.v1.Pagination
	11, // 1: tag.v1.ListRelationRequest.sort:type_name -> query.v1.Sort
	12, // 2: tag.v1.ListRelationRequest.data:type_name -> google.protobuf.Struct
	13, // 3: tag.v1.ListRelationResponse.data:type_name -> tag.v1.Relation
	12, // 4: tag.v1.SetRelationRequest.data:type_name -> google.protobuf.Struct
	0,  // 5: tag.v1.Relationship.ListRelation:input_type -> tag.v1.ListRelationRequest
	2,  // 6: tag.v1.Relationship.SetRelation:input_type -> tag.v1.SetRelationRequest
	4,  // 7: tag.v1.Relationship.DeleteRelation:input_type -> tag.v1.DeleteRelationRequest
	6,  // 8: tag.v1.Relationship.DestroyExternalRelation:input_type -> tag.v1.DestroyExternalRelationRequest
	8,  // 9: tag.v1.Relationship.DestroyTagRelation:input_type -> tag.v1.DestroyTagRelationRequest
	1,  // 10: tag.v1.Relationship.ListRelation:output_type -> tag.v1.ListRelationResponse
	3,  // 11: tag.v1.Relationship.SetRelation:output_type -> tag.v1.SetRelationResponse
	5,  // 12: tag.v1.Relationship.DeleteRelation:output_type -> tag.v1.DeleteRelationResponse
	7,  // 13: tag.v1.Relationship.DestroyExternalRelation:output_type -> tag.v1.DestroyExternalRelationResponse
	9,  // 14: tag.v1.Relationship.DestroyTagRelation:output_type -> tag.v1.DestroyTagRelationResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tag_v1_service_relation_proto_init() }
func file_tag_v1_service_relation_proto_init() {
	if File_tag_v1_service_relation_proto != nil {
		return
	}
	file_tag_v1_relation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tag_v1_service_relation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SetRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DestroyExternalRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DestroyExternalRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DestroyTagRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_relation_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DestroyTagRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tag_v1_service_relation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tag_v1_service_relation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_v1_service_relation_proto_goTypes,
		DependencyIndexes: file_tag_v1_service_relation_proto_depIdxs,
		MessageInfos:      file_tag_v1_service_relation_proto_msgTypes,
	}.Build()
	File_tag_v1_service_relation_proto = out.File
	file_tag_v1_service_relation_proto_rawDesc = nil
	file_tag_v1_service_relation_proto_goTypes = nil
	file_tag_v1_service_relation_proto_depIdxs = nil
}
