// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: tag/v1/service_base.proto

package tag

import (
	v1 "github.com/core-pb/dt/query/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *v1.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort       []*v1.Sort       `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty"`
	Id         []uint64         `protobuf:"fixed64,3,rep,packed,name=id,proto3" json:"id,omitempty"`
	Key        []string         `protobuf:"bytes,4,rep,name=key,proto3" json:"key,omitempty"`
	Info       *structpb.Struct `protobuf:"bytes,5,opt,name=info,proto3,oneof" json:"info,omitempty"`
}

func (x *ListModuleRequest) Reset() {
	*x = ListModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModuleRequest) ProtoMessage() {}

func (x *ListModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModuleRequest.ProtoReflect.Descriptor instead.
func (*ListModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{0}
}

func (x *ListModuleRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListModuleRequest) GetSort() []*v1.Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListModuleRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListModuleRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ListModuleRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*Module `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count int64     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListModuleResponse) Reset() {
	*x = ListModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModuleResponse) ProtoMessage() {}

func (x *ListModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModuleResponse.ProtoReflect.Descriptor instead.
func (*ListModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{1}
}

func (x *ListModuleResponse) GetData() []*Module {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListModuleResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64 `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SetModuleRequest) Reset() {
	*x = SetModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleRequest) ProtoMessage() {}

func (x *SetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleRequest.ProtoReflect.Descriptor instead.
func (*SetModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{2}
}

func (x *SetModuleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetModuleRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Module `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetModuleResponse) Reset() {
	*x = SetModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleResponse) ProtoMessage() {}

func (x *SetModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleResponse.ProtoReflect.Descriptor instead.
func (*SetModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{3}
}

func (x *SetModuleResponse) GetData() *Module {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetModuleInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64           `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Info *structpb.Struct `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SetModuleInfoRequest) Reset() {
	*x = SetModuleInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetModuleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleInfoRequest) ProtoMessage() {}

func (x *SetModuleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleInfoRequest.ProtoReflect.Descriptor instead.
func (*SetModuleInfoRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{4}
}

func (x *SetModuleInfoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetModuleInfoRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetModuleInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Module `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetModuleInfoResponse) Reset() {
	*x = SetModuleInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetModuleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleInfoResponse) ProtoMessage() {}

func (x *SetModuleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleInfoResponse.ProtoReflect.Descriptor instead.
func (*SetModuleInfoResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{5}
}

func (x *SetModuleInfoResponse) GetData() *Module {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateModuleVisibleTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	VisibleType []uint64 `protobuf:"fixed64,2,rep,packed,name=visible_type,json=visibleType,proto3" json:"visible_type,omitempty"`
}

func (x *UpdateModuleVisibleTypeRequest) Reset() {
	*x = UpdateModuleVisibleTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModuleVisibleTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleVisibleTypeRequest) ProtoMessage() {}

func (x *UpdateModuleVisibleTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleVisibleTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateModuleVisibleTypeRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateModuleVisibleTypeRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateModuleVisibleTypeRequest) GetVisibleType() []uint64 {
	if x != nil {
		return x.VisibleType
	}
	return nil
}

type UpdateModuleVisibleTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateModuleVisibleTypeResponse) Reset() {
	*x = UpdateModuleVisibleTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModuleVisibleTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleVisibleTypeResponse) ProtoMessage() {}

func (x *UpdateModuleVisibleTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleVisibleTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateModuleVisibleTypeResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{7}
}

type DeleteModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteModuleRequest) Reset() {
	*x = DeleteModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModuleRequest) ProtoMessage() {}

func (x *DeleteModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteModuleRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteModuleRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteModuleResponse) Reset() {
	*x = DeleteModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModuleResponse) ProtoMessage() {}

func (x *DeleteModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteModuleResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{9}
}

type ListTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *v1.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort       []*v1.Sort       `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty"`
	Id         []uint64         `protobuf:"fixed64,3,rep,packed,name=id,proto3" json:"id,omitempty"`
	Key        []string         `protobuf:"bytes,4,rep,name=key,proto3" json:"key,omitempty"`
	Info       *structpb.Struct `protobuf:"bytes,5,opt,name=info,proto3,oneof" json:"info,omitempty"`
	Inherit    *bool            `protobuf:"varint,6,opt,name=inherit,proto3,oneof" json:"inherit,omitempty"`
	Exclusive  *bool            `protobuf:"varint,7,opt,name=exclusive,proto3,oneof" json:"exclusive,omitempty"`
	ModuleId   []uint64         `protobuf:"fixed64,8,rep,packed,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
}

func (x *ListTypeRequest) Reset() {
	*x = ListTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypeRequest) ProtoMessage() {}

func (x *ListTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypeRequest.ProtoReflect.Descriptor instead.
func (*ListTypeRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{10}
}

func (x *ListTypeRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTypeRequest) GetSort() []*v1.Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListTypeRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListTypeRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ListTypeRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ListTypeRequest) GetInherit() bool {
	if x != nil && x.Inherit != nil {
		return *x.Inherit
	}
	return false
}

func (x *ListTypeRequest) GetExclusive() bool {
	if x != nil && x.Exclusive != nil {
		return *x.Exclusive
	}
	return false
}

func (x *ListTypeRequest) GetModuleId() []uint64 {
	if x != nil {
		return x.ModuleId
	}
	return nil
}

type ListTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*Type `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count int64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListTypeResponse) Reset() {
	*x = ListTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypeResponse) ProtoMessage() {}

func (x *ListTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypeResponse.ProtoReflect.Descriptor instead.
func (*ListTypeResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{11}
}

func (x *ListTypeResponse) GetData() []*Type {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTypeResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64 `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SetTypeRequest) Reset() {
	*x = SetTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypeRequest) ProtoMessage() {}

func (x *SetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypeRequest.ProtoReflect.Descriptor instead.
func (*SetTypeRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{12}
}

func (x *SetTypeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTypeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Type `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetTypeResponse) Reset() {
	*x = SetTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypeResponse) ProtoMessage() {}

func (x *SetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypeResponse.ProtoReflect.Descriptor instead.
func (*SetTypeResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{13}
}

func (x *SetTypeResponse) GetData() *Type {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetTypeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64           `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Info *structpb.Struct `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SetTypeInfoRequest) Reset() {
	*x = SetTypeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypeInfoRequest) ProtoMessage() {}

func (x *SetTypeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypeInfoRequest.ProtoReflect.Descriptor instead.
func (*SetTypeInfoRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{14}
}

func (x *SetTypeInfoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTypeInfoRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetTypeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Type `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetTypeInfoResponse) Reset() {
	*x = SetTypeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypeInfoResponse) ProtoMessage() {}

func (x *SetTypeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypeInfoResponse.ProtoReflect.Descriptor instead.
func (*SetTypeInfoResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{15}
}

func (x *SetTypeInfoResponse) GetData() *Type {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateTypeInheritRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	Inherit bool     `protobuf:"varint,2,opt,name=inherit,proto3" json:"inherit,omitempty"`
}

func (x *UpdateTypeInheritRequest) Reset() {
	*x = UpdateTypeInheritRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTypeInheritRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeInheritRequest) ProtoMessage() {}

func (x *UpdateTypeInheritRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeInheritRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypeInheritRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTypeInheritRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateTypeInheritRequest) GetInherit() bool {
	if x != nil {
		return x.Inherit
	}
	return false
}

type UpdateTypeInheritResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTypeInheritResponse) Reset() {
	*x = UpdateTypeInheritResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTypeInheritResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeInheritResponse) ProtoMessage() {}

func (x *UpdateTypeInheritResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeInheritResponse.ProtoReflect.Descriptor instead.
func (*UpdateTypeInheritResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{17}
}

type UpdateTypeExclusiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	Exclusive bool     `protobuf:"varint,2,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
}

func (x *UpdateTypeExclusiveRequest) Reset() {
	*x = UpdateTypeExclusiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTypeExclusiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeExclusiveRequest) ProtoMessage() {}

func (x *UpdateTypeExclusiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeExclusiveRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypeExclusiveRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateTypeExclusiveRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateTypeExclusiveRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type UpdateTypeExclusiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTypeExclusiveResponse) Reset() {
	*x = UpdateTypeExclusiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTypeExclusiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeExclusiveResponse) ProtoMessage() {}

func (x *UpdateTypeExclusiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeExclusiveResponse.ProtoReflect.Descriptor instead.
func (*UpdateTypeExclusiveResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{19}
}

type DeleteTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTypeRequest) Reset() {
	*x = DeleteTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTypeRequest) ProtoMessage() {}

func (x *DeleteTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTypeRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteTypeRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTypeResponse) Reset() {
	*x = DeleteTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTypeResponse) ProtoMessage() {}

func (x *DeleteTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteTypeResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{21}
}

type ListTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *v1.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort       []*v1.Sort       `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty"`
	Id         []uint64         `protobuf:"fixed64,3,rep,packed,name=id,proto3" json:"id,omitempty"`
	Key        []string         `protobuf:"bytes,4,rep,name=key,proto3" json:"key,omitempty"`
	TypeId     []uint64         `protobuf:"fixed64,5,rep,packed,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	ParentId   []uint64         `protobuf:"fixed64,6,rep,packed,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Data       *structpb.Struct `protobuf:"bytes,7,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Info       *structpb.Struct `protobuf:"bytes,8,opt,name=info,proto3,oneof" json:"info,omitempty"`
	ModuleId   []uint64         `protobuf:"fixed64,9,rep,packed,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{22}
}

func (x *ListTagRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTagRequest) GetSort() []*v1.Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListTagRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListTagRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ListTagRequest) GetTypeId() []uint64 {
	if x != nil {
		return x.TypeId
	}
	return nil
}

func (x *ListTagRequest) GetParentId() []uint64 {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *ListTagRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTagRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ListTagRequest) GetModuleId() []uint64 {
	if x != nil {
		return x.ModuleId
	}
	return nil
}

type ListTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*Tag `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListTagResponse) Reset() {
	*x = ListTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagResponse) ProtoMessage() {}

func (x *ListTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagResponse.ProtoReflect.Descriptor instead.
func (*ListTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{23}
}

func (x *ListTagResponse) GetData() []*Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTagResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64           `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Key      string           `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	TypeId   uint64           `protobuf:"fixed64,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	ParentId uint64           `protobuf:"fixed64,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Data     *structpb.Struct `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Info     *structpb.Struct `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *AddTagRequest) Reset() {
	*x = AddTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagRequest) ProtoMessage() {}

func (x *AddTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagRequest.ProtoReflect.Descriptor instead.
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{24}
}

func (x *AddTagRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddTagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddTagRequest) GetTypeId() uint64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AddTagRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddTagRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddTagRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type AddTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Tag `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddTagResponse) Reset() {
	*x = AddTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagResponse) ProtoMessage() {}

func (x *AddTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagResponse.ProtoReflect.Descriptor instead.
func (*AddTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{25}
}

func (x *AddTagResponse) GetData() *Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64           `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetTagRequest) Reset() {
	*x = SetTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagRequest) ProtoMessage() {}

func (x *SetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagRequest.ProtoReflect.Descriptor instead.
func (*SetTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{26}
}

func (x *SetTagRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTagRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Tag `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetTagResponse) Reset() {
	*x = SetTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagResponse) ProtoMessage() {}

func (x *SetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagResponse.ProtoReflect.Descriptor instead.
func (*SetTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{27}
}

func (x *SetTagResponse) GetData() *Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetTagInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64           `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Info *structpb.Struct `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SetTagInfoRequest) Reset() {
	*x = SetTagInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagInfoRequest) ProtoMessage() {}

func (x *SetTagInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagInfoRequest.ProtoReflect.Descriptor instead.
func (*SetTagInfoRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{28}
}

func (x *SetTagInfoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTagInfoRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetTagInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Tag `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetTagInfoResponse) Reset() {
	*x = SetTagInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagInfoResponse) ProtoMessage() {}

func (x *SetTagInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagInfoResponse.ProtoReflect.Descriptor instead.
func (*SetTagInfoResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{29}
}

func (x *SetTagInfoResponse) GetData() *Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateTagTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	TypeId uint64   `protobuf:"fixed64,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
}

func (x *UpdateTagTypeRequest) Reset() {
	*x = UpdateTagTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagTypeRequest) ProtoMessage() {}

func (x *UpdateTagTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagTypeRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateTagTypeRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateTagTypeRequest) GetTypeId() uint64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type UpdateTagTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTagTypeResponse) Reset() {
	*x = UpdateTagTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagTypeResponse) ProtoMessage() {}

func (x *UpdateTagTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagTypeResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{31}
}

type UpdateTagParentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	ParentId uint64   `protobuf:"fixed64,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
}

func (x *UpdateTagParentRequest) Reset() {
	*x = UpdateTagParentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagParentRequest) ProtoMessage() {}

func (x *UpdateTagParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagParentRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagParentRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateTagParentRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateTagParentRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type UpdateTagParentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTagParentResponse) Reset() {
	*x = UpdateTagParentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagParentResponse) ProtoMessage() {}

func (x *UpdateTagParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagParentResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagParentResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{33}
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteTagRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_v1_service_base_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_v1_service_base_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_v1_service_base_proto_rawDescGZIP(), []int{35}
}

var File_tag_v1_service_base_proto protoreflect.FileDescriptor

var file_tag_v1_service_base_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x1a, 0x19, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x13, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x30, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x4e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37,
	0x0a, 0x11, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3b, 0x0a, 0x15,
	0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x1e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x76,
	0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x06, 0x52, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x21,
	0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x69,
	0x73, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xc1, 0x02, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88,
	0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x07, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x88, 0x01,
	0x01, 0x12, 0x21, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x03, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49,
	0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x69,
	0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x22, 0x4a, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x32, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x33, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x12, 0x53, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x37, 0x0a, 0x13,
	0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd5,
	0x02, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x06, 0x52, 0x06,
	0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x06, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x01, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x03, 0x28, 0x06, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x49, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x48, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xc1, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61,
	0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x54,
	0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x3f, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65,
	0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcf, 0x0a, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x19, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x26, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x12, 0x20, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e,
	0x68, 0x65, 0x72, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x60, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12, 0x22, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x78, 0x63, 0x6c,
	0x75, 0x73, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x12, 0x16,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x12, 0x15, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x06,
	0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x12, 0x15, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x54, 0x61,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x12, 0x18, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x54, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x70, 0x62, 0x2f, 0x74,
	0x61, 0x67, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x61, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tag_v1_service_base_proto_rawDescOnce sync.Once
	file_tag_v1_service_base_proto_rawDescData = file_tag_v1_service_base_proto_rawDesc
)

func file_tag_v1_service_base_proto_rawDescGZIP() []byte {
	file_tag_v1_service_base_proto_rawDescOnce.Do(func() {
		file_tag_v1_service_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_tag_v1_service_base_proto_rawDescData)
	})
	return file_tag_v1_service_base_proto_rawDescData
}

var file_tag_v1_service_base_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_tag_v1_service_base_proto_goTypes = []any{
	(*ListModuleRequest)(nil),               // 0: tag.v1.ListModuleRequest
	(*ListModuleResponse)(nil),              // 1: tag.v1.ListModuleResponse
	(*SetModuleRequest)(nil),                // 2: tag.v1.SetModuleRequest
	(*SetModuleResponse)(nil),               // 3: tag.v1.SetModuleResponse
	(*SetModuleInfoRequest)(nil),            // 4: tag.v1.SetModuleInfoRequest
	(*SetModuleInfoResponse)(nil),           // 5: tag.v1.SetModuleInfoResponse
	(*UpdateModuleVisibleTypeRequest)(nil),  // 6: tag.v1.UpdateModuleVisibleTypeRequest
	(*UpdateModuleVisibleTypeResponse)(nil), // 7: tag.v1.UpdateModuleVisibleTypeResponse
	(*DeleteModuleRequest)(nil),             // 8: tag.v1.DeleteModuleRequest
	(*DeleteModuleResponse)(nil),            // 9: tag.v1.DeleteModuleResponse
	(*ListTypeRequest)(nil),                 // 10: tag.v1.ListTypeRequest
	(*ListTypeResponse)(nil),                // 11: tag.v1.ListTypeResponse
	(*SetTypeRequest)(nil),                  // 12: tag.v1.SetTypeRequest
	(*SetTypeResponse)(nil),                 // 13: tag.v1.SetTypeResponse
	(*SetTypeInfoRequest)(nil),              // 14: tag.v1.SetTypeInfoRequest
	(*SetTypeInfoResponse)(nil),             // 15: tag.v1.SetTypeInfoResponse
	(*UpdateTypeInheritRequest)(nil),        // 16: tag.v1.UpdateTypeInheritRequest
	(*UpdateTypeInheritResponse)(nil),       // 17: tag.v1.UpdateTypeInheritResponse
	(*UpdateTypeExclusiveRequest)(nil),      // 18: tag.v1.UpdateTypeExclusiveRequest
	(*UpdateTypeExclusiveResponse)(nil),     // 19: tag.v1.UpdateTypeExclusiveResponse
	(*DeleteTypeRequest)(nil),               // 20: tag.v1.DeleteTypeRequest
	(*DeleteTypeResponse)(nil),              // 21: tag.v1.DeleteTypeResponse
	(*ListTagRequest)(nil),                  // 22: tag.v1.ListTagRequest
	(*ListTagResponse)(nil),                 // 23: tag.v1.ListTagResponse
	(*AddTagRequest)(nil),                   // 24: tag.v1.AddTagRequest
	(*AddTagResponse)(nil),                  // 25: tag.v1.AddTagResponse
	(*SetTagRequest)(nil),                   // 26: tag.v1.SetTagRequest
	(*SetTagResponse)(nil),                  // 27: tag.v1.SetTagResponse
	(*SetTagInfoRequest)(nil),               // 28: tag.v1.SetTagInfoRequest
	(*SetTagInfoResponse)(nil),              // 29: tag.v1.SetTagInfoResponse
	(*UpdateTagTypeRequest)(nil),            // 30: tag.v1.UpdateTagTypeRequest
	(*UpdateTagTypeResponse)(nil),           // 31: tag.v1.UpdateTagTypeResponse
	(*UpdateTagParentRequest)(nil),          // 32: tag.v1.UpdateTagParentRequest
	(*UpdateTagParentResponse)(nil),         // 33: tag.v1.UpdateTagParentResponse
	(*DeleteTagRequest)(nil),                // 34: tag.v1.DeleteTagRequest
	(*DeleteTagResponse)(nil),               // 35: tag.v1.DeleteTagResponse
	(*v1.Pagination)(nil),                   // 36: query.v1.Pagination
	(*v1.Sort)(nil),                         // 37: query.v1.Sort
	(*structpb.Struct)(nil),                 // 38: google.protobuf.Struct
	(*Module)(nil),                          // 39: tag.v1.Module
	(*Type)(nil),                            // 40: tag.v1.Type
	(*Tag)(nil),                             // 41: tag.v1.Tag
}
var file_tag_v1_service_base_proto_depIdxs = []int32{
	36, // 0: tag.v1.ListModuleRequest.pagination:type_name -> query.v1.Pagination
	37, // 1: tag.v1.ListModuleRequest.sort:type_name -> query.v1.Sort
	38, // 2: tag.v1.ListModuleRequest.info:type_name -> google.protobuf.Struct
	39, // 3: tag.v1.ListModuleResponse.data:type_name -> tag.v1.Module
	39, // 4: tag.v1.SetModuleResponse.data:type_name -> tag.v1.Module
	38, // 5: tag.v1.SetModuleInfoRequest.info:type_name -> google.protobuf.Struct
	39, // 6: tag.v1.SetModuleInfoResponse.data:type_name -> tag.v1.Module
	36, // 7: tag.v1.ListTypeRequest.pagination:type_name -> query.v1.Pagination
	37, // 8: tag.v1.ListTypeRequest.sort:type_name -> query.v1.Sort
	38, // 9: tag.v1.ListTypeRequest.info:type_name -> google.protobuf.Struct
	40, // 10: tag.v1.ListTypeResponse.data:type_name -> tag.v1.Type
	40, // 11: tag.v1.SetTypeResponse.data:type_name -> tag.v1.Type
	38, // 12: tag.v1.SetTypeInfoRequest.info:type_name -> google.protobuf.Struct
	40, // 13: tag.v1.SetTypeInfoResponse.data:type_name -> tag.v1.Type
	36, // 14: tag.v1.ListTagRequest.pagination:type_name -> query.v1.Pagination
	37, // 15: tag.v1.ListTagRequest.sort:type_name -> query.v1.Sort
	38, // 16: tag.v1.ListTagRequest.data:type_name -> google.protobuf.Struct
	38, // 17: tag.v1.ListTagRequest.info:type_name -> google.protobuf.Struct
	41, // 18: tag.v1.ListTagResponse.data:type_name -> tag.v1.Tag
	38, // 19: tag.v1.AddTagRequest.data:type_name -> google.protobuf.Struct
	38, // 20: tag.v1.AddTagRequest.info:type_name -> google.protobuf.Struct
	41, // 21: tag.v1.AddTagResponse.data:type_name -> tag.v1.Tag
	38, // 22: tag.v1.SetTagRequest.data:type_name -> google.protobuf.Struct
	41, // 23: tag.v1.SetTagResponse.data:type_name -> tag.v1.Tag
	38, // 24: tag.v1.SetTagInfoRequest.info:type_name -> google.protobuf.Struct
	41, // 25: tag.v1.SetTagInfoResponse.data:type_name -> tag.v1.Tag
	0,  // 26: tag.v1.Base.ListModule:input_type -> tag.v1.ListModuleRequest
	2,  // 27: tag.v1.Base.SetModule:input_type -> tag.v1.SetModuleRequest
	4,  // 28: tag.v1.Base.SetModuleInfo:input_type -> tag.v1.SetModuleInfoRequest
	8,  // 29: tag.v1.Base.DeleteModule:input_type -> tag.v1.DeleteModuleRequest
	6,  // 30: tag.v1.Base.UpdateModuleVisibleType:input_type -> tag.v1.UpdateModuleVisibleTypeRequest
	10, // 31: tag.v1.Base.ListType:input_type -> tag.v1.ListTypeRequest
	12, // 32: tag.v1.Base.SetType:input_type -> tag.v1.SetTypeRequest
	14, // 33: tag.v1.Base.SetTypeInfo:input_type -> tag.v1.SetTypeInfoRequest
	20, // 34: tag.v1.Base.DeleteType:input_type -> tag.v1.DeleteTypeRequest
	16, // 35: tag.v1.Base.UpdateTypeInherit:input_type -> tag.v1.UpdateTypeInheritRequest
	18, // 36: tag.v1.Base.UpdateTypeExclusive:input_type -> tag.v1.UpdateTypeExclusiveRequest
	22, // 37: tag.v1.Base.ListTag:input_type -> tag.v1.ListTagRequest
	24, // 38: tag.v1.Base.AddTag:input_type -> tag.v1.AddTagRequest
	26, // 39: tag.v1.Base.SetTag:input_type -> tag.v1.SetTagRequest
	28, // 40: tag.v1.Base.SetTagInfo:input_type -> tag.v1.SetTagInfoRequest
	34, // 41: tag.v1.Base.DeleteTag:input_type -> tag.v1.DeleteTagRequest
	30, // 42: tag.v1.Base.UpdateTagType:input_type -> tag.v1.UpdateTagTypeRequest
	32, // 43: tag.v1.Base.UpdateTagParent:input_type -> tag.v1.UpdateTagParentRequest
	1,  // 44: tag.v1.Base.ListModule:output_type -> tag.v1.ListModuleResponse
	3,  // 45: tag.v1.Base.SetModule:output_type -> tag.v1.SetModuleResponse
	5,  // 46: tag.v1.Base.SetModuleInfo:output_type -> tag.v1.SetModuleInfoResponse
	9,  // 47: tag.v1.Base.DeleteModule:output_type -> tag.v1.DeleteModuleResponse
	7,  // 48: tag.v1.Base.UpdateModuleVisibleType:output_type -> tag.v1.UpdateModuleVisibleTypeResponse
	11, // 49: tag.v1.Base.ListType:output_type -> tag.v1.ListTypeResponse
	13, // 50: tag.v1.Base.SetType:output_type -> tag.v1.SetTypeResponse
	15, // 51: tag.v1.Base.SetTypeInfo:output_type -> tag.v1.SetTypeInfoResponse
	21, // 52: tag.v1.Base.DeleteType:output_type -> tag.v1.DeleteTypeResponse
	17, // 53: tag.v1.Base.UpdateTypeInherit:output_type -> tag.v1.UpdateTypeInheritResponse
	19, // 54: tag.v1.Base.UpdateTypeExclusive:output_type -> tag.v1.UpdateTypeExclusiveResponse
	23, // 55: tag.v1.Base.ListTag:output_type -> tag.v1.ListTagResponse
	25, // 56: tag.v1.Base.AddTag:output_type -> tag.v1.AddTagResponse
	27, // 57: tag.v1.Base.SetTag:output_type -> tag.v1.SetTagResponse
	29, // 58: tag.v1.Base.SetTagInfo:output_type -> tag.v1.SetTagInfoResponse
	35, // 59: tag.v1.Base.DeleteTag:output_type -> tag.v1.DeleteTagResponse
	31, // 60: tag.v1.Base.UpdateTagType:output_type -> tag.v1.UpdateTagTypeResponse
	33, // 61: tag.v1.Base.UpdateTagParent:output_type -> tag.v1.UpdateTagParentResponse
	44, // [44:62] is the sub-list for method output_type
	26, // [26:44] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_tag_v1_service_base_proto_init() }
func file_tag_v1_service_base_proto_init() {
	if File_tag_v1_service_base_proto != nil {
		return
	}
	file_tag_v1_module_proto_init()
	file_tag_v1_tag_proto_init()
	file_tag_v1_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tag_v1_service_base_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SetModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetModuleInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetModuleInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateModuleVisibleTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateModuleVisibleTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SetTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SetTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SetTypeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SetTypeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTypeInheritRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTypeInheritResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTypeExclusiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTypeExclusiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*ListTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*ListTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*AddTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*AddTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTagTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTagTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTagParentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTagParentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_v1_service_base_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tag_v1_service_base_proto_msgTypes[0].OneofWrappers = []any{}
	file_tag_v1_service_base_proto_msgTypes[10].OneofWrappers = []any{}
	file_tag_v1_service_base_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tag_v1_service_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_v1_service_base_proto_goTypes,
		DependencyIndexes: file_tag_v1_service_base_proto_depIdxs,
		MessageInfos:      file_tag_v1_service_base_proto_msgTypes,
	}.Build()
	File_tag_v1_service_base_proto = out.File
	file_tag_v1_service_base_proto_rawDesc = nil
	file_tag_v1_service_base_proto_goTypes = nil
	file_tag_v1_service_base_proto_depIdxs = nil
}
