name: Release

on:
  push:
    tags:
      - "v*"

jobs:
#  buf-module:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: stable
#
#      - uses: bufbuild/buf-action@v1
#        with:
#          token: ${{ secrets.BUF_TOKEN }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: corepbx/tag:${{ github.ref_name }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            COMMIT_DATE=${{ github.event.head_commit.timestamp }}
            GIT_TAG=${{ github.ref_name }}

      - name: Get latest tag
        run: |
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          echo "Latest tag is: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Update latest tag if necessary
        if: startsWith(github.ref_name, 'v') && github.ref_name != env.LATEST_TAG
        run: |
          docker tag corepbx/tag:${{ github.ref_name }} corepbx/tag:latest
          docker push corepbx/tag:latest
